fix logging error in 8.1 caused by system/core credits: @Adarsh-MR
with reference to the following log:
In file included from system/core/liblog/include/log/log.h:32:0,
                 from system/core/libutils/include/utils/Vector.h:23,
                 from frameworks/av/camera/include/camera/CameraMetadata.h:23,
                 from device/xiaomi/msm8956-common/camera/QCamera2/HAL3/QCamera3HWI.cpp:36:
device/xiaomi/msm8956-common/camera/QCamera2/HAL3/QCamera3HWI.cpp: In member function 'int qcamera::QCamera3HardwareInterface::validateCaptureRequest(camera3_capture_request_t*)':
system/core/liblog/include/log/log_main.h:61:45: error: too many arguments for format [-Werror=format-extra-args]
   __android_log_print(prio, tag, __VA_ARGS__)
                                             ^
system/core/liblog/include/log/log_main.h:70:37: note: in expansion of macro 'android_printLog'
 #define LOG_PRI(priority, tag, ...) android_printLog(priority, tag, __VA_ARGS__)
                                     ^
system/core/liblog/include/log/log_main.h:306:34: note: in expansion of macro 'LOG_PRI'
 #define ALOG(priority, tag, ...) LOG_PRI(ANDROID_##priority, tag, __VA_ARGS__)
                                  ^
system/core/liblog/include/log/log_main.h:240:27: note: in expansion of macro 'ALOG'
 #define ALOGE(...) ((void)ALOG(LOG_ERROR, LOG_TAG, __VA_ARGS__))
                           ^
device/xiaomi/msm8956-common/camera/QCamera2/HAL3/QCamera3HWI.cpp:1731:9: note: in expansion of macro 'ALOGE'
         ALOGE("%s: Number of buffers %d equals or is greater than maximum number of streams!",
         ^
device/xiaomi/msm8956-common/camera/QCamera2/HAL3/QCamera3HWI.cpp: In member function 'int qcamera::QCamera3HardwareInterface::flushPerf()':
system/core/liblog/include/log/log_main.h:61:45: error: format '%s' expects a matching 'char*' argument [-Werror=format=]
   __android_log_print(prio, tag, __VA_ARGS__)
                                             ^
system/core/liblog/include/log/log_main.h:70:37: note: in expansion of macro 'android_printLog'
 #define LOG_PRI(priority, tag, ...) android_printLog(priority, tag, __VA_ARGS__)
                                     ^
system/core/liblog/include/log/log_main.h:306:34: note: in expansion of macro 'LOG_PRI'
 #define ALOG(priority, tag, ...) LOG_PRI(ANDROID_##priority, tag, __VA_ARGS__)
                                  ^
system/core/liblog/include/log/log_main.h:206:37: note: in expansion of macro 'ALOG'
   ((__predict_false(cond)) ? ((void)ALOG(LOG_DEBUG, LOG_TAG, __VA_ARGS__)) \
                                     ^
device/xiaomi/msm8956-common/camera/QCamera2/HAL3/QCamera3HWI.h:52:28: note: in expansion of macro 'ALOGD_IF'
 #define CDBG(fmt, args...) ALOGD_IF(gCamHal3LogLevel >= 2, fmt, ##args)
                            ^
device/xiaomi/msm8956-common/camera/QCamera2/HAL3/QCamera3HWI.cpp:3364:9: note: in expansion of macro 'CDBG'
         CDBG("%s: No pending buffers in the HAL, return flush");
         ^
cc1plus: all warnings being treated as errors